steps:
  - id: Cancel Previous Builds
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        # 同じトリガーからの実行中のビルドを取得（自分以外）
        RUNNING_BUILDS=$$(gcloud builds list \
          --ongoing \
          --filter="buildTriggerId=$_TRIGGER_ID AND id!=$BUILD_ID" \
          --format="value(id)" \
          --project=$_AR_PROJECT_ID)

        # 実行中のビルドがあればキャンセル
        if [ -n "$RUNNING_BUILDS" ]; then
          echo "Cancelling previous builds: $RUNNING_BUILDS"
          for BUILD in $RUNNING_BUILDS; do
            gcloud builds cancel "$BUILD" --project=$_AR_PROJECT_ID || true
          done
        else
          echo "No previous builds to cancel"
        fi

  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - "-f"
      - Dockerfile

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

  - id: Apply Migrations
    name: gcr.io/google-appengine/exec-wrapper
    entrypoint: "bash"
    secretEnv: ["RAILS_MASTER_KEY"]
    args:
      - -c
      - |
        /buildstep/execute.sh \
          -i $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          -e RAILS_ENV=production \
          -e RAILS_MASTER_KEY=$$RAILS_MASTER_KEY \
          -- bundle exec rails db:migrate

  - id: Import Data
    name: gcr.io/google-appengine/exec-wrapper
    entrypoint: "bash"
    secretEnv: ["RAILS_MASTER_KEY"]
    args:
      - -c
      - |
        /buildstep/execute.sh \
          -i $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          -e RAILS_ENV=production \
          -e RAILS_MASTER_KEY=$$RAILS_MASTER_KEY \
          -- bundle exec rake data:import

  - id: Deploy
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--remove-env-vars=GOOGLE_PRIVATE_KEY,GOOGLE_PRIVATE_KEY_ID,GOOGLE_APPLICATION_CREDENTIALS"
      - "--quiet"
    entrypoint: gcloud

images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: asia-northeast1
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: ramen-ai
  _SERVICE_NAME: ramen-ai-backend-service
availableSecrets:
  secretManager:
    - versionName: projects/943228427206/secrets/RAILS_MASTER_KEY/versions/2
      env: "RAILS_MASTER_KEY"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - ramen-ai-backend-service
