name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ramen_ai_backend_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".tool-versions"
          bundler-cache: true

      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:prepare

      - name: Run RuboCop
        run: |
          bundle exec rubocop

      - name: Run RSpec
        run: |
          bundle exec rspec --format progress --color
